---
collections: []
roles:
  - src: https://github.com/mrlesmithjr/ansible-bootstrap-python.git
  - src: https://github.com/mrlesmithjr/ansible-postgresql
  - src: https://github.com/mrlesmithjr/ansible-redis
