---
- name: "Check bacula-Dir Config"
  command: "{{ bacula_dir_binary }} -t -c {{ bacula_dir_config }}"
  register: bacula_dir_config_check
  ignore_errors: yes
  delegate_to: "{{ bacula_dir_fqdn_ssh }}"

- name: "Start bacula-dir"
  service:
    name: "{{ bacula_dir_service_name_delegated }}"
    state: started
  delegate_to: "{{ bacula_dir_fqdn_ssh }}"
  run_once: true
  when:
  - bacula_restart_services

- name: "Restart bacula-dir"
  service:
    name: "{{ bacula_dir_service_name_delegated }}"
    state: restarted
  delegate_to: "{{ bacula_dir_fqdn_ssh }}"
  run_once: true
  when:
  - bacula_restart_services

- name: "Reload bacula-dir"
  service:
    name: "{{ bacula_dir_service_name_delegated }}"
    state: reloaded
  run_once: true
  delegate_to: "{{ bacula_dir_fqdn_ssh }}"
  when:
  - bacula_reload_services

- name: "Start bacula-sd"
  service:
    name: "{{ bacula_sd_service_name }}"
    state: started
  when:
  - bacula_sd_role
  - bacula_restart_services

- name: "Restart bacula-sd"
  service:
    name: "{{ bacula_sd_service_name }}"
    state: restarted
  when:
  - bacula_sd_role
  - bacula_restart_services

- name: "Start bacula-fd"
  service:
    name: "{{ bacula_fd_service_name }}"
    state: started

- name: "Restart bacula-fd"
  service:
    name: "{{ bacula_fd_service_name }}"
    state: restarted

- name: "Start bacula-fd (Windows)"
  service:
    name: "{{ bacula_fd_service_name }}"
    state: started

- name: "Restart bacula-fd (Windows)"
  win_service:
    name: "{{ bacula_fd_service_name }}"
    state: restarted
